

def redis_conf():
    return {
        'host': '127.0.0.1',
        'port': '6379',
        'db': 0,
    }


def redis_jobs():
    return {
        'filter': 'proxy:jobs:filter',
        'validate': 'proxy:jobs:validate',
    }


def redis_services():
    return {
        'general': 'proxy:service:general',
        '58': 'proxy:service:58',
        'ganji': 'proxy:service:ganji',
        '0511web': 'proxy:service:0511:web',
        '0511wap': 'proxy:service:0511:wap'
    }


def proxy_sites():
    return [
        'http://pachong.org/area/city/name/上海.html',
        'http://pachong.org/area/city/name/上饶.html',
        'http://pachong.org/area/city/name/东莞.html',
        'http://pachong.org/area/city/name/东营.html',
        'http://pachong.org/area/city/name/中国.html',
        'http://pachong.org/area/city/name/中山.html',
        'http://pachong.org/area/city/name/临汾.html',
        'http://pachong.org/area/city/name/丹东.html',
        'http://pachong.org/area/city/name/乌鲁木齐.html',
        'http://pachong.org/area/city/name/九江.html',
        'http://pachong.org/area/city/name/六盘水.html',
        'http://pachong.org/area/city/name/兰州.html',
        'http://pachong.org/area/city/name/北京.html',
        'http://pachong.org/area/city/name/南京.html',
        'http://pachong.org/area/city/name/南宁.html',
        'http://pachong.org/area/city/name/南昌.html',
        'http://pachong.org/area/city/name/南通.html',
        'http://pachong.org/area/city/name/南阳.html',
        'http://pachong.org/area/city/name/厦门.html',
        'http://pachong.org/area/city/name/台湾.html',
        'http://pachong.org/area/city/name/合肥.html',
        'http://pachong.org/area/city/name/吉林.html',
        'http://pachong.org/area/city/name/周口.html',
        'http://pachong.org/area/city/name/呼和浩特.html',
        'http://pachong.org/area/city/name/哈尔滨.html',
        'http://pachong.org/area/city/name/唐山.html',
        'http://pachong.org/area/city/name/商丘.html',
        'http://pachong.org/area/city/name/嘉兴.html',
        'http://pachong.org/area/city/name/天津.html',
        'http://pachong.org/area/city/name/太原.html',
        'http://pachong.org/area/city/name/宁波.html',
        'http://pachong.org/area/city/name/安阳.html',
        'http://pachong.org/area/city/name/宜春.html',
        'http://pachong.org/area/city/name/宝鸡.html',
        'http://pachong.org/area/city/name/常州.html',
        'http://pachong.org/area/city/name/广州.html',
        'http://pachong.org/area/city/name/廊坊.html',
        'http://pachong.org/area/city/name/德州.html',
        'http://pachong.org/area/city/name/成都.html',
        'http://pachong.org/area/city/name/扬州.html',
        'http://pachong.org/area/city/name/揭阳.html',
        'http://pachong.org/area/city/name/新乡.html',
        'http://pachong.org/area/city/name/新余.html',
        'http://pachong.org/area/city/name/无锡.html',
        'http://pachong.org/area/city/name/曲靖.html',
        'http://pachong.org/area/city/name/杭州.html',
        'http://pachong.org/area/city/name/榆林.html',
        'http://pachong.org/area/city/name/武汉.html',
        'http://pachong.org/area/city/name/汕头.html',
        'http://pachong.org/area/city/name/江门.html',
        'http://pachong.org/area/city/name/沈阳.html',
        'http://pachong.org/area/city/name/洛阳.html',
        'http://pachong.org/area/city/name/济南.html',
        'http://pachong.org/area/city/name/深圳.html',
        'http://pachong.org/area/city/name/温州.html',
        'http://pachong.org/area/city/name/湛江.html',
        'http://pachong.org/area/city/name/潍坊.html',
        'http://pachong.org/area/city/name/潜江.html',
        'http://pachong.org/area/city/name/澳门.html',
        'http://pachong.org/area/city/name/烟台.html',
        'http://pachong.org/area/city/name/珠海.html',
        'http://pachong.org/area/city/name/盐城.html',
        'http://pachong.org/area/city/name/福州.html',
        'http://pachong.org/area/city/name/红河.html',
        'http://pachong.org/area/city/name/绍兴.html',
        'http://pachong.org/area/city/name/苏州.html',
        'http://pachong.org/area/city/name/萍乡.html',
        'http://pachong.org/area/city/name/许昌.html',
        'http://pachong.org/area/city/name/调试.html',
        'http://pachong.org/area/city/name/赣州.html',
        'http://pachong.org/area/city/name/郑州.html',
        'http://pachong.org/area/city/name/重庆.html',
        'http://pachong.org/area/city/name/金华.html',
        'http://pachong.org/area/city/name/镇江.html',
        'http://pachong.org/area/city/name/长春.html',
        'http://pachong.org/area/city/name/长沙.html',
        'http://pachong.org/area/city/name/青岛.html',
        'http://pachong.org/area/city/name/香港.html',
        'http://pachong.org/area/city/name/鹰潭.html',
        'http://pachong.org/area/city/name/黄冈.html',
        'http://pachong.org/area/short/name/ae.html',
        'http://pachong.org/area/short/name/af.html',
        'http://pachong.org/area/short/name/al.html',
        'http://pachong.org/area/short/name/ar.html',
        'http://pachong.org/area/short/name/at.html',
        'http://pachong.org/area/short/name/au.html',
        'http://pachong.org/area/short/name/ba.html',
        'http://pachong.org/area/short/name/bd.html',
        'http://pachong.org/area/short/name/bg.html',
        'http://pachong.org/area/short/name/br.html',
        'http://pachong.org/area/short/name/by.html',
        'http://pachong.org/area/short/name/bz.html',
        'http://pachong.org/area/short/name/ca.html',
        'http://pachong.org/area/short/name/ch.html',
        'http://pachong.org/area/short/name/cm.html',
        'http://pachong.org/area/short/name/co.html',
        'http://pachong.org/area/short/name/cr.html',
        'http://pachong.org/area/short/name/cs.html',
        'http://pachong.org/area/short/name/de.html',
        'http://pachong.org/area/short/name/ec.html',
        'http://pachong.org/area/short/name/eg.html',
        'http://pachong.org/area/short/name/es.html',
        'http://pachong.org/area/short/name/fr.html',
        'http://pachong.org/area/short/name/gb.html',
        'http://pachong.org/area/short/name/ge.html',
        'http://pachong.org/area/short/name/gr.html',
        'http://pachong.org/area/short/name/hr.html',
        'http://pachong.org/area/short/name/hu.html',
        'http://pachong.org/area/short/name/il.html',
        'http://pachong.org/area/short/name/in.html',
        'http://pachong.org/area/short/name/iq.html',
        'http://pachong.org/area/short/name/ir.html',
        'http://pachong.org/area/short/name/it.html',
        'http://pachong.org/area/short/name/jp.html',
        'http://pachong.org/area/short/name/ke.html',
        'http://pachong.org/area/short/name/kh.html',
        'http://pachong.org/area/short/name/kr.html',
        'http://pachong.org/area/short/name/lb.html',
        'http://pachong.org/area/short/name/lt.html',
        'http://pachong.org/area/short/name/ma.html',
        'http://pachong.org/area/short/name/md.html',
        'http://pachong.org/area/short/name/ml.html',
        'http://pachong.org/area/short/name/mn.html',
        'http://pachong.org/area/short/name/mx.html',
        'http://pachong.org/area/short/name/my.html',
        'http://pachong.org/area/short/name/ng.html',
        'http://pachong.org/area/short/name/nl.html',
        'http://pachong.org/area/short/name/pe.html',
        'http://pachong.org/area/short/name/ph.html',
        'http://pachong.org/area/short/name/pk.html',
        'http://pachong.org/area/short/name/pl.html',
        'http://pachong.org/area/short/name/py.html',
        'http://pachong.org/area/short/name/ro.html',
        'http://pachong.org/area/short/name/ru.html',
        'http://pachong.org/area/short/name/sa.html',
        'http://pachong.org/area/short/name/se.html',
        'http://pachong.org/area/short/name/sg.html',
        'http://pachong.org/area/short/name/si.html',
        'http://pachong.org/area/short/name/sy.html',
        'http://pachong.org/area/short/name/tn.html',
        'http://pachong.org/area/short/name/tr.html',
        'http://pachong.org/area/short/name/ua.html',
        'http://pachong.org/area/short/name/us.html',
        'http://pachong.org/area/short/name/ve.html',
        'http://pachong.org/area/short/name/vn.html',
        'http://pachong.org/area/short/name/za.html',
        'http://proxy.com.ru/niming/',
        'http://proxy.com.ru/gaoni/',
        'http://www.proxy360.cn/Proxy',
        'http://cn-proxy.com/archives/218',
        'http://www.ipdizhi.com/all.html',
        'http://www.site-digger.com/html/articles/20110516/proxieslist.html',
        'http://proxy.ipcn.org/proxylist.html',
        'http://www.cnproxy.com/proxy1.html',
        'http://www.cnproxy.com/proxy2.html',
        'http://www.cnproxy.com/proxy3.html',
        'http://www.cnproxy.com/proxy4.html',
        'http://www.cnproxy.com/proxy5.html',
        'http://www.cnproxy.com/proxy6.html',
        'http://www.cnproxy.com/proxy7.html',
        'http://www.cnproxy.com/proxy8.html',
        'http://www.cnproxy.com/proxy9.html',
        'http://www.cnproxy.com/proxy10.html',
    ]
